### ISSUE TITLE
cargo build failure

### ISSUE THREAD

**Issue by generalelectrix** [cbourjau/alice-rs#3]
When I try to run cargo build, cargo fails with this error:

```bash
~/src/alice-rs$ cargo build
error: failed to read `~/src/alice-sys/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Looks like `malice` is set up with a relative path dependency to a different repo checked out on your local machine.

**Comment by cbourjau** [comment]
Thanks a lot for reporting this! Should be fixed now
